# -*- mode: ruby -*-
# vi: set ft=ruby :



Vagrant.configure(2) do |config|

	config.hostmanager.enabled = true
	config.hostmanager.ignore_private_ip = false
	config.hostmanager.include_offline = true

	config.vm.define "puppet" do |puppet|
	 config.vm.provider "virtualbox" do |v|
	   v.memory = 2048
	 end
	 puppet.vm.synced_folder ".", "/vagrant"
	 puppet.vm.synced_folder "../code","/puppet_code"
	 puppet.vm.synced_folder "../puppetserver", "/puppet_puppetserver"
   	 config.vm.box = "box-cutter/centos72"
	 puppet.vm.hostname = "puppet.example.com"
   	 puppet.vm.network "private_network", ip: "10.0.0.10"
	 puppet.hostmanager.aliases = %w(puppet)
	 puppet.vm.provision "shell", inline: <<-SHELL
	    sudo yum update -y
	    sudo rpm -ivh http://yum.puppet.com/puppet6-release-el-7.noarch.rpm
	    sudo yum install puppetserver -y
	    sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
	  SHELL
	end

	config.vm.define "agent1" do |agent1|
  	 config.vm.box = "centos/7"
	 agent1.vm.hostname = "agent1.example.com"
    	 agent1.vm.network "private_network", ip: "10.0.0.11"
	 agent1.hostmanager.aliases = %w(agent1)

	end
end
